### PR TITLE
deps: integrate `camunda-modeler-webpack-plugins`

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Uses [`camunda-modeler-webpack-plugin`](https://github.com/camunda/camunda-modeler-webpack-plugin) to get rid of needed properties panel configurations.

**before**
```js
module.exports = {
  mode: 'development',
  entry: './client/client.js',
  output: {
    path: path.resolve(__dirname, 'client'),
    filename: 'client-bundle.js'
  },
  devtool: 'cheap-module-source-map',
  resolve: {
    alias: {
      '@bpmn-io/properties-panel': 'camunda-modeler-plugin-helpers/vendor/@bpmn-io/properties-panel',
      'bpmn-js-properties-panel': 'camunda-modeler-plugin-helpers/vendor/bpmn-js-properties-panel'
    }
  }
};
```

**after**
```js
module.exports = {
  mode: 'development',
  entry: './client/client.js',
  output: {
    path: path.resolve(__dirname, 'client'),
    filename: 'client-bundle.js'
  },
  devtool: 'cheap-module-source-map',
  plugins: [
    new CamundaModelerWebpackPlugin()
  ]
};
```

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Since we don't need the [JSX transformation](https://github.com/camunda/camunda-modeler-process-io-specification-plugin/pull/23/files#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166f) anymore, I think I will make this piece configurable.

**Comment by pinussilvestrus** [comment]
This is ready, but needs a first release of the[ webpack plugins ](https://github.com/pinussilvestrus/camunda-modeler-webpack-plugins)to be ready for review.

**Comment by pinussilvestrus** [comment]
Another thing to be considered: https://github.com/camunda/camunda-modeler-webpack-plugins/issues/1

**Comment by pinussilvestrus** [comment]
This is ready for review now 👍

**Review by barmac — APPROVED** [review]

**Pull request merged**
